Repository CMU-313/fall23-nodebb-qwerty-coders, pull requests merged in 2023-10, with the labels that each got.

#31 FEATURE - Add endorsement and endorsement message
  public/openapi/write.yaml
  public/openapi/write/posts/pid/endorse.yaml
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/api/posts.js
  src/controllers/write/posts.js
  src/posts/endorse.js
  src/posts/endorse.ts
  src/posts/index.js
  src/routes/write/posts.js
  src/topics/posts.js
  test/posts.js
  themes/nodebb-theme-persona/less/topic.less
  themes/nodebb-theme-persona/templates/partials/topic/endorse-msg.tpl
  themes/nodebb-theme-persona/templates/partials/topic/endorse-toggle.tpl
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: enhancement, post status feature

#37 User documentation file creation
  UserGuide.md
Labels: documentation

#38 Added private label UI in list view and on topic
  patches/nodebb-plugin-composer-default+9.2.4.patch
  src/database/index.js
  src/privileges/topics.js
  src/topics/create.js
  src/topics/data.js
  themes/nodebb-theme-persona/less/topic.less
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
  themes/nodebb-theme-persona/templates/private-tag-preview.tpl
  themes/nodebb-theme-persona/templates/private-tag-topic.tpl
  themes/nodebb-theme-persona/templates/topic.tpl
Labels: enhancement, private post feature

#39 Changed font size for private label
  themes/nodebb-theme-persona/less/topic.less
Labels: private post feature

#41 Fix private topic field incorrectly shown after merge
  src/topics/data.js
Labels: bug, private post feature

#42 Test for creating private post
  test/topics.js
Labels: private post feature

#40 Limit endorse button to instructors
  public/openapi/read/topic/topic_id.yaml
  src/api/posts.js
  src/posts/endorse.js
  src/posts/endorse.ts
  src/privileges/topics.js
  test/posts.js
  themes/nodebb-theme-persona/less/topic.less
  themes/nodebb-theme-persona/templates/partials/topic/endorse-msg.tpl
  themes/nodebb-theme-persona/templates/partials/topic/endorse-toggle.tpl
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: post status feature

#44 Private topic section of UserGuide
  UserGuide.md
Labels: documentation, private post feature

#46 Post status indicators in topic view
  src/posts/endorse.js
  src/posts/endorse.ts
  src/topics/teaser.js
  test/topics.js
  themes/nodebb-theme-persona/less/topics_list.less
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: enhancement, post status feature

#47 Fix lint error from previous PR
  src/topics/teaser.js
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: bug, post status feature

#48 Update UserGuide.md for Post Endorsements
  UserGuide.md
Labels: documentation, post status feature

#49 Add back private topic related UI features
  themes/nodebb-theme-persona/templates/partials/topics_list.tpl
Labels: private post feature

#45 Redis schema for Instructors and TAs
  src/database/redis/instructors.js
  src/database/redis/instructors.ts
Labels: account identity
